program ab23hc;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  uBrand.SQLBuilder.MySQL in 'App\Module\Brand\Infra\Repository\SQLBuilder\MySQL\uBrand.SQLBuilder.MySQL.pas',
  uBrand in 'App\Module\Brand\Domain\Entity\uBrand.pas',
  uAclUser in 'App\Module\AclUser\Domain\Entity\uAclUser.pas',
  uAclRole in 'App\Module\AclRole\Domain\Entity\uAclRole.pas',
  uBrand.StoreAndShow.UseCase in 'App\Module\Brand\Application\UseCase\uBrand.StoreAndShow.UseCase.pas',
  uBase.Entity in 'App\Shared\Domain\Entity\uBase.Entity.pas',
  uValidation.Interfaces in 'App\Shared\Domain\Validation\uValidation.Interfaces.pas',
  uBase.Repository in 'App\Shared\Infra\Repository\uBase.Repository.pas',
  uAclRole.UpdateAndShow.UseCase in 'App\Module\AclRole\Application\UseCase\uAclRole.UpdateAndShow.UseCase.pas',
  uAclRole.Show.DTO in 'App\Module\AclRole\Application\DTO\uAclRole.Show.DTO.pas',
  uAclUser.Show.DTO in 'App\Module\AclUser\Application\DTO\uAclUser.Show.DTO.pas',
  uAclRole.Show.UseCase in 'App\Module\AclRole\Application\UseCase\uAclRole.Show.UseCase.pas',
  uAclRole.StoreAndShow.UseCase in 'App\Module\AclRole\Application\UseCase\uAclRole.StoreAndShow.UseCase.pas',
  uAclUser.Show.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.Show.UseCase.pas',
  uAclUser.StoreAndShow.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.StoreAndShow.UseCase.pas',
  uAclUser.UpdateAndShow.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.UpdateAndShow.UseCase.pas',
  uBrand.Show.UseCase in 'App\Module\Brand\Application\UseCase\uBrand.Show.UseCase.pas',
  uBrand.UpdateAndShow.UseCase in 'App\Module\Brand\Application\UseCase\uBrand.UpdateAndShow.UseCase.pas',
  uBrand.Show.DTO in 'App\Module\Brand\Application\DTO\uBrand.Show.DTO.pas',
  uAclUser.Auth.Me.DTO in 'App\Module\AclUser\Application\DTO\uAclUser.Auth.Me.DTO.pas',
  uAclUser.Auth.Controller in 'App\Module\AclUser\Infra\Controller\uAclUser.Auth.Controller.pas',
  uAclUser.Auth.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.Auth.UseCase.pas',
  uAclUser.Auth.ChangePassword.DTO in 'App\Module\AclUser\Application\DTO\uAclUser.Auth.ChangePassword.DTO.pas',
  uAclUser.Auth.Login.DTO in 'App\Module\AclUser\Application\DTO\uAclUser.Auth.Login.DTO.pas',
  uAclUser.Controller in 'App\Module\AclUser\Infra\Controller\uAclUser.Controller.pas',
  uMyClaims in 'Config\Infra\uMyClaims.pas',
  uAclUser.Repository.SQL in 'App\Module\AclUser\Infra\Repository\SQL\uAclUser.Repository.SQL.pas',
  uAclUser.SQLBuilder.Interfaces in 'App\Module\AclUser\Domain\Repository\uAclUser.SQLBuilder.Interfaces.pas',
  uAclUser.SQLBuilder in 'App\Module\AclUser\Infra\Repository\SQLBuilder\uAclUser.SQLBuilder.pas',
  uAclUser.Repository.Interfaces in 'App\Module\AclUser\Domain\Repository\uAclUser.Repository.Interfaces.pas',
  uRouteApi in 'Route\Api\uRouteApi.pas',
  uAclUser.DTO in 'App\Module\AclUser\Application\DTO\uAclUser.DTO.pas',
  uAclUser.Index.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.Index.UseCase.pas',
  uAclUser.Delete.UseCase in 'App\Module\AclUser\Application\UseCase\uAclUser.Delete.UseCase.pas',
  uAclRole.Controller in 'App\Module\AclRole\Infra\Controller\uAclRole.Controller.pas',
  uAclRole.Index.UseCase in 'App\Module\AclRole\Application\UseCase\uAclRole.Index.UseCase.pas',
  uAclRole.Delete.UseCase in 'App\Module\AclRole\Application\UseCase\uAclRole.Delete.UseCase.pas',
  uAclRole.DTO in 'App\Module\AclRole\Application\DTO\uAclRole.DTO.pas',
  uBrand.DTO in 'App\Module\Brand\Application\DTO\uBrand.DTO.pas',
  uExceptionHandler in 'App\Exceptions\Infra\uExceptionHandler.pas',
  uMain in 'uMain.pas',
  uBrand.Controller in 'App\Module\Brand\Infra\Controller\uBrand.Controller.pas',
  uResponse.DTO in 'App\Shared\Application\DTO\uResponse.DTO.pas',
  uBrand.Index.UseCase in 'App\Module\Brand\Application\UseCase\uBrand.Index.UseCase.pas',
  uPageFilter in 'App\Shared\Application\Util\uPageFilter.pas',
  uBrand.Delete.UseCase in 'App\Module\Brand\Application\UseCase\uBrand.Delete.UseCase.pas',
  uApplication.Types in 'App\Shared\Application\Types\uApplication.Types.pas',
  uBrand.SQLBuilder in 'App\Module\Brand\Infra\Repository\SQLBuilder\uBrand.SQLBuilder.pas',
  uHlp in 'App\Shared\Application\Util\uHlp.pas',
  uRes in 'App\Shared\Application\Util\uRes.pas',
  uFormRequest in 'App\Shared\Application\Util\uFormRequest.pas',
  uBrand.Repository.SQL in 'App\Module\Brand\Infra\Repository\SQL\uBrand.Repository.SQL.pas',
  uEnv in 'Config\Infra\uEnv.pas',
  uRepository.Factory in 'App\Shared\Infra\Repository\uRepository.Factory.pas',
  uSQLBuilder.Factory in 'App\Shared\Infra\Repository\SQLBuilder\uSQLBuilder.Factory.pas',
  uAclRole.Repository.SQL in 'App\Module\AclRole\Infra\Repository\SQL\uAclRole.Repository.SQL.pas',
  uAclRole.Repository.Interfaces in 'App\Module\AclRole\Domain\Repository\uAclRole.Repository.Interfaces.pas',
  uBrand.Repository.Interfaces in 'App\Module\Brand\Domain\Repository\uBrand.Repository.Interfaces.pas',
  uBase.Repository.Interfaces in 'App\Shared\Domain\Repository\uBase.Repository.Interfaces.pas',
  uAclUser.SQLBuilder.MySQL in 'App\Module\AclUser\Infra\Repository\SQLBuilder\MySQL\uAclUser.SQLBuilder.MySQL.pas',
  uAclRole.SQLBuilder.MySQL in 'App\Module\AclRole\Infra\Repository\SQLBuilder\MySQL\uAclRole.SQLBuilder.MySQL.pas',
  uAclRole.SQLBuilder.Interfaces in 'App\Module\AclRole\Domain\Repository\uAclRole.SQLBuilder.Interfaces.pas',
  uAclRole.SQLBuilder in 'App\Module\AclRole\Infra\Repository\SQLBuilder\uAclRole.SQLBuilder.pas',
  uBrand.SQLBuilder.Interfaces in 'App\Module\Brand\Domain\Repository\uBrand.SQLBuilder.Interfaces.pas',
  uBase.SQLBuilder.Interfaces in 'App\Shared\Domain\Repository\uBase.SQLBuilder.Interfaces.pas',
  uConnection.Types in 'Database\Application\uConnection.Types.pas',
  uAutomaticPingInConsole.Task in 'App\TaskScheduler\Infra\Task\uAutomaticPingInConsole.Task.pas',
  uTaskScheduler in 'App\TaskScheduler\Infra\uTaskScheduler.pas',
  uSelectWithFilter in 'App\Shared\Application\Util\uSelectWithFilter.pas',
  uQtdStr in 'App\Shared\Application\Util\uQtdStr.pas',
  uConnection.Interfaces in 'Database\Domain\Connection\uConnection.Interfaces.pas',
  uIndexResult in 'App\Shared\Application\Util\uIndexResult.pas',
  uConnection.Factory in 'Database\Infra\Connection\uConnection.Factory.pas',
  uScript.Factory in 'Database\Infra\Connection\uScript.Factory.pas',
  uQry.Factory in 'Database\Infra\Connection\uQry.Factory.pas',
  uMemTable.Factory in 'Database\Infra\Connection\uMemTable.Factory.pas',
  uMemTable.Interfaces in 'Database\Domain\Connection\uMemTable.Interfaces.pas',
  uScript.Interfaces in 'Database\Domain\Connection\uScript.Interfaces.pas',
  uQry.Interfaces in 'Database\Domain\Connection\uQry.Interfaces.pas',
  uConnection.FireDAC in 'Database\Infra\Connection\FireDAC\uConnection.FireDAC.pas',
  uMemTable.FireDAC in 'Database\Infra\Connection\FireDAC\uMemTable.FireDAC.pas',
  uQry.FireDAC in 'Database\Infra\Connection\FireDAC\uQry.FireDAC.pas',
  uScript.FireDAC in 'Database\Infra\Connection\FireDAC\uScript.FireDAC.pas',
  uMigration.Interfaces in 'Database\Domain\Migration\uMigration.Interfaces.pas',
  uMigration.Base in 'Database\Infra\Migration\Manager\uMigration.Base.pas',
  uMigration.Helper in 'Database\Infra\Migration\Manager\uMigration.Helper.pas',
  uMigration.Info in 'Database\Infra\Migration\Manager\uMigration.Info.pas',
  uMigration.Manager in 'Database\Infra\Migration\Manager\uMigration.Manager.pas',
  u02CreateAclRoleTable.Migration in 'Database\Infra\Migration\u02CreateAclRoleTable.Migration.pas',
  u03CreateAclUserTable.Migration in 'Database\Infra\Migration\u03CreateAclUserTable.Migration.pas',
  u04CreateBrandTable.Migration in 'Database\Infra\Migration\u04CreateBrandTable.Migration.pas',
  u05AclRoleSeed.Migration in 'Database\Infra\Migration\u05AclRoleSeed.Migration.pas',
  u06AclUserSeed.Migration in 'Database\Infra\Migration\u06AclUserSeed.Migration.pas';

begin
  TMain.Start;
end.
