program ab23hc;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  uAclUser.Controller in 'App\Module\AclUser\Controller\uAclUser.Controller.pas',
  uApplication.Types in 'App\Shared\Types\uApplication.Types.pas',
  uExceptionHandler in 'App\Exceptions\uExceptionHandler.pas',
  uRes in 'App\Shared\Util\uRes.pas',
  uAclUser.Auth.ChangePassword.DTO in 'App\Module\AclUser\DTO\uAclUser.Auth.ChangePassword.DTO.pas',
  uPageFilter in 'App\Shared\Util\uPageFilter.pas',
  uBrand.Controller in 'App\Module\Brand\Controller\uBrand.Controller.pas',
  uRouteApi in 'Route\Api\uRouteApi.pas',
  uAclUser in 'App\Module\AclUser\Entity\uAclUser.pas',
  uBrand in 'App\Module\Brand\Entity\uBrand.pas',
  uQtdStr in 'App\Shared\Util\uQtdStr.pas',
  uAclUser.Repository.Interfaces in 'App\Module\AclUser\Repository\uAclUser.Repository.Interfaces.pas',
  uAclUser.Repository.SQL in 'App\Module\AclUser\Repository\SQL\uAclUser.Repository.SQL.pas',
  uQry.FireDAC in 'Database\Connection\Drivers\FireDAC\uQry.FireDAC.pas',
  uConnection.FireDAC in 'Database\Connection\Drivers\FireDAC\uConnection.FireDAC.pas',
  uHlp in 'App\Shared\Util\uHlp.pas',
  uIndexResult in 'App\Shared\Util\uIndexResult.pas',
  uSelectWithFilter in 'App\Shared\Util\uSelectWithFilter.pas',
  uBrand.Repository.SQL in 'App\Module\Brand\Repository\SQL\uBrand.Repository.SQL.pas',
  uBrand.Repository.Interfaces in 'App\Module\Brand\Repository\uBrand.Repository.Interfaces.pas',
  uEnv in 'Config\uEnv.pas',
  uBrand.SQLBuilder.Interfaces in 'App\Module\Brand\SQLBuilder\uBrand.SQLBuilder.Interfaces.pas',
  uConnection.Types in 'Database\Connection\uConnection.Types.pas',
  uConnection.Factory in 'Database\Connection\uConnection.Factory.pas',
  uScript.Factory in 'Database\Connection\uScript.Factory.pas',
  uQry.Factory in 'Database\Connection\uQry.Factory.pas',
  uMemTable.Factory in 'Database\Connection\uMemTable.Factory.pas',
  uMemTable.Interfaces in 'Database\Connection\uMemTable.Interfaces.pas',
  uMemTable.FireDAC in 'Database\Connection\Drivers\FireDAC\uMemTable.FireDAC.pas',
  uConnection.Interfaces in 'Database\Connection\uConnection.Interfaces.pas',
  uQry.Interfaces in 'Database\Connection\uQry.Interfaces.pas',
  uScript.Interfaces in 'Database\Connection\uScript.Interfaces.pas',
  uScript.FireDAC in 'Database\Connection\Drivers\FireDAC\uScript.FireDAC.pas',
  uEither in 'App\Shared\Util\uEither.pas',
  uMyClaims in 'Config\uMyClaims.pas',
  System.Classes,
  uMigration.Base in 'Database\Migration\uMigration.Base.pas',
  uMigration.Helper in 'Database\Migration\uMigration.Helper.pas',
  uMigration.Info in 'Database\Migration\uMigration.Info.pas',
  uMigration.Interfaces in 'Database\Migration\uMigration.Interfaces.pas',
  uMigration.Manager in 'Database\Migration\uMigration.Manager.pas',
  u02CreateAclRoleTable.Migration in 'Database\Migration\u02CreateAclRoleTable.Migration.pas',
  u03CreateAclUserTable.Migration in 'Database\Migration\u03CreateAclUserTable.Migration.pas',
  u04CreateBrandTable.Migration in 'Database\Migration\u04CreateBrandTable.Migration.pas',
  uMain in 'uMain.pas',
  uTaskScheduler in 'App\TaskScheduler\uTaskScheduler.pas',
  uAutomaticPingInConsole.Task in 'App\TaskScheduler\Task\uAutomaticPingInConsole.Task.pas',
  uBrand.SQLBuilder in 'App\Module\Brand\SQLBuilder\uBrand.SQLBuilder.pas',
  uBrand.SQLBuilder.MySQL in 'App\Module\Brand\SQLBuilder\MySQL\uBrand.SQLBuilder.MySQL.pas',
  uAclUser.SQLBuilder.Interfaces in 'App\Module\AclUser\SQLBuilder\uAclUser.SQLBuilder.Interfaces.pas',
  uAclUser.SQLBuilder in 'App\Module\AclUser\SQLBuilder\uAclUser.SQLBuilder.pas',
  uAclUser.SQLBuilder.MySQL in 'App\Module\AclUser\SQLBuilder\MySQL\uAclUser.SQLBuilder.MySQL.pas',
  uBase.SQLBuilder.Interfaces in 'App\Shared\SQLBuilder\uBase.SQLBuilder.Interfaces.pas',
  uBase.Entity in 'App\Shared\Entity\uBase.Entity.pas',
  uBase.Repository.Interfaces in 'App\Shared\Repository\uBase.Repository.Interfaces.pas',
  uBase.Repository in 'App\Shared\Repository\uBase.Repository.pas',
  uAclRole.SQLBuilder in 'App\Module\AclRole\SQLBuilder\uAclRole.SQLBuilder.pas',
  uAclRole.SQLBuilder.MySQL in 'App\Module\AclRole\SQLBuilder\MySQL\uAclRole.SQLBuilder.MySQL.pas',
  uAclRole.Controller in 'App\Module\AclRole\Controller\uAclRole.Controller.pas',
  uAclRole.SQLBuilder.Interfaces in 'App\Module\AclRole\SQLBuilder\uAclRole.SQLBuilder.Interfaces.pas',
  uAclRole.Repository.Interfaces in 'App\Module\AclRole\Repository\uAclRole.Repository.Interfaces.pas',
  uAclRole.Repository.SQL in 'App\Module\AclRole\Repository\SQL\uAclRole.Repository.SQL.pas',
  uAclRole in 'App\Module\AclRole\Entity\uAclRole.pas',
  uSQLBuilder.Factory in 'App\Shared\SQLBuilder\uSQLBuilder.Factory.pas',
  uRepository.Factory in 'App\Shared\Repository\uRepository.Factory.pas',
  uFormRequest in 'App\Shared\Util\uFormRequest.pas',
  uBrand.DTO in 'App\Module\Brand\DTO\uBrand.DTO.pas',
  uBrand.StoreAndShow.UseCase in 'App\Module\Brand\UseCase\uBrand.StoreAndShow.UseCase.pas',
  uBrand.Show.DTO in 'App\Module\Brand\DTO\uBrand.Show.DTO.pas',
  uBrand.Show.UseCase in 'App\Module\Brand\UseCase\uBrand.Show.UseCase.pas',
  uBrand.UpdateAndShow.UseCase in 'App\Module\Brand\UseCase\uBrand.UpdateAndShow.UseCase.pas',
  uResponse.DTO in 'App\Shared\DTO\uResponse.DTO.pas',
  uBrand.Delete.UseCase in 'App\Module\Brand\UseCase\uBrand.Delete.UseCase.pas',
  uBrand.Index.UseCase in 'App\Module\Brand\UseCase\uBrand.Index.UseCase.pas',
  uAclRole.Show.DTO in 'App\Module\AclRole\DTO\uAclRole.Show.DTO.pas',
  uAclRole.DTO in 'App\Module\AclRole\DTO\uAclRole.DTO.pas',
  uAclRole.Delete.UseCase in 'App\Module\AclRole\UseCase\uAclRole.Delete.UseCase.pas',
  uAclRole.Index.UseCase in 'App\Module\AclRole\UseCase\uAclRole.Index.UseCase.pas',
  uAclRole.Show.UseCase in 'App\Module\AclRole\UseCase\uAclRole.Show.UseCase.pas',
  uAclRole.StoreAndShow.UseCase in 'App\Module\AclRole\UseCase\uAclRole.StoreAndShow.UseCase.pas',
  uAclRole.UpdateAndShow.UseCase in 'App\Module\AclRole\UseCase\uAclRole.UpdateAndShow.UseCase.pas',
  uAclUser.Show.DTO in 'App\Module\AclUser\DTO\uAclUser.Show.DTO.pas',
  uAclUser.DTO in 'App\Module\AclUser\DTO\uAclUser.DTO.pas',
  uAclUser.Delete.UseCase in 'App\Module\AclUser\UseCase\uAclUser.Delete.UseCase.pas',
  uAclUser.Index.UseCase in 'App\Module\AclUser\UseCase\uAclUser.Index.UseCase.pas',
  uAclUser.Show.UseCase in 'App\Module\AclUser\UseCase\uAclUser.Show.UseCase.pas',
  uAclUser.StoreAndShow.UseCase in 'App\Module\AclUser\UseCase\uAclUser.StoreAndShow.UseCase.pas',
  uAclUser.UpdateAndShow.UseCase in 'App\Module\AclUser\UseCase\uAclUser.UpdateAndShow.UseCase.pas',
  uAclUser.Auth.Login.DTO in 'App\Module\AclUser\DTO\uAclUser.Auth.Login.DTO.pas',
  uAclUser.Auth.UseCase in 'App\Module\AclUser\UseCase\uAclUser.Auth.UseCase.pas',
  uAclUser.Auth.Controller in 'App\Module\AclUser\Controller\uAclUser.Auth.Controller.pas',
  uAclUser.Auth.Me.DTO in 'App\Module\AclUser\DTO\uAclUser.Auth.Me.DTO.pas';

begin
  TMain.Start;
end.
