unit uCFOP.SQLBuilder.MySQL;

interface

uses
  uCFOP.SQLBuilder,
  uCFOP.SQLBuilder.Interfaces;

type
  TCFOPSQLBuilderMySQL = class(TCFOPSQLBuilder, ICFOPSQLBuilder)
  public
    constructor Create;
    class function Make: ICFOPSQLBuilder;
    function ScriptCreateTable: String; override;
    function ScriptSeedTable: String; override;
  end;

implementation

uses
  cqlbr.interfaces,
  uSmartPointer,
  System.Classes;

{ TCFOPSQLBuilderMySQL }

constructor TCFOPSQLBuilderMySQL.Create;
begin
  inherited Create;
  FDBName := dbnMySQL;
end;

class function TCFOPSQLBuilderMySQL.Make: ICFOPSQLBuilder;
begin
  Result := Self.Create;
end;

function TCFOPSQLBuilderMySQL.ScriptCreateTable: String;
begin
  Result := ' CREATE TABLE `cfop` ( '+
            '   `id` bigint(20) NOT NULL AUTO_INCREMENT, '+
            '   `name` varchar(255) NOT NULL, '+
            '   `code` varchar(10) NOT NULL, '+
            '   `operation_type` tinyint(4) NOT NULL COMMENT ''[0..1] 0-Entrada, 1-Saída'', '+
            '   `created_at` datetime DEFAULT NULL, '+
            '   `updated_at` datetime DEFAULT NULL, '+
            '   `created_by_acl_user_id` bigint(20) DEFAULT NULL, '+
            '   `updated_by_acl_user_id` bigint(20) DEFAULT NULL, '+
            '   PRIMARY KEY (`id`), '+
            '   KEY `cfop_idx_name` (`name`), '+
            '   KEY `cfop_fk_created_by_acl_user_id` (`created_by_acl_user_id`), '+
            '   KEY `cfop_fk_updated_by_acl_role_id` (`updated_by_acl_user_id`), '+
            '   CONSTRAINT `cfop_fk_created_by_acl_user_id` FOREIGN KEY (`created_by_acl_user_id`) REFERENCES `acl_user` (`id`), '+
            '   CONSTRAINT `cfop_fk_updated_by_acl_role_id` FOREIGN KEY (`updated_by_acl_user_id`) REFERENCES `acl_user` (`id`) '+
            ' )  ';
end;

function TCFOPSQLBuilderMySQL.ScriptSeedTable: String;
var
  lStrList: Shared<TStringList>;
begin
  lStrList := TStringList.Create;
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (1,''1101'',''Compra para industrialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (2,''1102'',''Compra para comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (3,''1111'',''Compra para industrialização de mercadoria recebida anteriormente em consignação industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (4,''1113'',''Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (5,''1116'',''Compra para industrialização originada de encomenda para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (6,''1117'',''Compra para comercialização originada de encomenda para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (7,''1118'',''Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (8,''1120'',''Compra para industrialização, em venda à ordem, já recebida do vendedor remetente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (9,''1121'',''Compra para comercialização, em venda à ordem, já recebida do vendedor remetente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (10,''1122'',''Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (11,''1124'',''Industrialização efetuada por outra empresa'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (12,''1125'',''Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estab'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (13,''1126'',''Compra para utilização na prestação de serviço'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (14,''1151'',''Transferência para industrialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (15,''1152'',''Transferência para comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (16,''1153'',''Transferência de energia elétrica para distribuição'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (17,''1154'',''Transferência para utilização na prestação de serviço'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (18,''1201'',''Devolução de venda de produção do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (19,''1202'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (20,''1203'',''Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (21,''1204'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (22,''1205'',''Anulação de valor relativo à prestação de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (23,''1206'',''Anulação de valor relativo à prestação de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (24,''1207'',''Anulação de valor relativo à venda de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (25,''1208'',''Devolução de produção do estabelecimento, remetida em transferência'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (26,''1209'',''Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (27,''1251'',''Compra de energia elétrica para distribuição ou comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (28,''1252'',''Compra de energia elétrica por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (29,''1253'',''Compra de energia elétrica por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (30,''1254'',''Compra de energia elétrica por estabelecimento prestador de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (31,''1255'',''Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (32,''1256'',''Compra de energia elétrica por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (33,''1257'',''Compra de energia elétrica para consumo por demanda contratada'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (34,''1301'',''Aquisição de serviço de comunicação para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (35,''1302'',''Aquisição de serviço de comunicação por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (36,''1303'',''Aquisição de serviço de comunicação por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (37,''1304'',''Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (38,''1305'',''Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (39,''1306'',''Aquisição de serviço de comunicação por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (40,''1351'',''Aquisição de serviço de transporte para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (41,''1352'',''Aquisição de serviço de transporte por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (42,''1353'',''Aquisição de serviço de transporte por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (43,''1354'',''Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (44,''1355'',''Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (45,''1356'',''Aquisição de serviço de transporte por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (46,''1401'',''Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (47,''1403'',''Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (48,''1406'',''Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (49,''1407'',''Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (50,''1408'',''Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (51,''1409'',''Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (52,''1410'',''Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (53,''1411'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (54,''1414'',''Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (55,''1415'',''Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (56,''1451'',''Retorno de animal do estabelecimento produtor'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (57,''1452'',''Retorno de insumo não utilizado na produção'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (58,''1501'',''Entrada de mercadoria recebida com fim específico de exportação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (59,''1503'',''Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (60,''1504'',''Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (61,''1551'',''Compra de bem para o ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (62,''1552'',''Transferência de bem do ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (63,''1553'',''Devolução de venda de bem do ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (64,''1554'',''Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (65,''1555'',''Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (66,''1556'',''Compra de material para uso ou consumo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (67,''1557'',''Transferência de material para uso ou consumo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (68,''1601'',''Recebimento, por transferência, de crédito de ICMS'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (69,''1602'',''Recebimento, por transferência, de saldo credor de ICMS de outro estabelecimento da mesma empresa, para compensação de saldo devedor de ICMS'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (70,''1603'',''Ressarcimento de ICMS retido por substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (71,''1604'',''Lançamento do crédito relativo à compra de bem para o ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (72,''1901'',''Entrada para industrialização por encomenda'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (73,''1902'',''Retorno de mercadoria remetida para industrialização por encomenda'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (74,''1903'',''Entrada de mercadoria remetida para industrialização e não aplicada no referido processo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (75,''1904'',''Retorno de remessa para venda fora do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (76,''1905'',''Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (77,''1906'',''Retorno de mercadoria remetida para depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (78,''1907'',''Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (79,''1908'',''Entrada de bem por conta de contrato de comodato'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (80,''1909'',''Retorno de bem remetido por conta de contrato de comodato'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (81,''1910'',''Entrada de bonificação, doação ou brinde'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (82,''1911'',''Entrada de amostra grátis'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (83,''1912'',''Entrada de mercadoria ou bem recebido para demonstração'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (84,''1913'',''Retorno de mercadoria ou bem remetido para demonstração'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (85,''1914'',''Retorno de mercadoria ou bem remetido para exposição ou feira'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (86,''1915'',''Entrada de mercadoria ou bem recebido para conserto ou reparo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (87,''1916'',''Retorno de mercadoria ou bem remetido para conserto ou reparo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (88,''1917'',''Entrada de mercadoria recebida em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (89,''1918'',''Devolução de mercadoria remetida em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (90,''1919'',''Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (91,''1920'',''Entrada de vasilhame ou sacaria'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (92,''1921'',''Retorno de vasilhame ou sacaria'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (93,''1922'',''Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (94,''1923'',''Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (95,''1924'',''Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (96,''1925'',''Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (97,''1926'',''Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (98,''1949'',''Outra entrada de mercadoria ou prestação de serviço não especificada'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (99,''2101'',''Compra para industrialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (100,''2102'',''Compra para comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (101,''2111'',''Compra para industrialização de mercadoria recebida anteriormente em consignação industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (102,''2113'',''Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (103,''2116'',''Compra para industrialização originada de encomenda para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (104,''2117'',''Compra para comercialização originada de encomenda para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (105,''2118'',''Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (106,''2120'',''Compra para industrialização, em venda à ordem, já recebida do vendedor remetente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (107,''2121'',''Compra para comercialização, em venda à ordem, já recebida do vendedor remetente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (108,''2122'',''Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (109,''2124'',''Industrialização efetuada por outra empresa'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (110,''2125'',''Industrialização efetuada por outra empresa quando a mercadoria remetida para utilização no processo de industrialização não transitou pelo estabelecimento adq'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (111,''2126'',''Compra para utilização na prestação de serviço'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (112,''2151'',''Transferência para industrialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (113,''2152'',''Transferência para comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (114,''2153'',''Transferência de energia elétrica para distribuição'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (115,''2154'',''Transferência para utilização na prestação de serviço'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (116,''2201'',''Devolução de venda de produção do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (117,''2202'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (118,''2203'',''Devolução de venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (119,''2204'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (120,''2205'',''Anulação de valor relativo à prestação de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (121,''2206'',''Anulação de valor relativo à prestação de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (122,''2207'',''Anulação de valor relativo à venda de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (123,''2208'',''Devolução de produção do estabelecimento, remetida em transferência'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (124,''2209'',''Devolução de mercadoria adquirida ou recebida de terceiros, remetida em transferência'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (125,''2251'',''Compra de energia elétrica para distribuição ou comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (126,''2252'',''Compra de energia elétrica por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (127,''2253'',''Compra de energia elétrica por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (128,''2254'',''Compra de energia elétrica por estabelecimento prestador de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (129,''2255'',''Compra de energia elétrica por estabelecimento prestador de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (130,''2256'',''Compra de energia elétrica por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (131,''2257'',''Compra de energia elétrica para consumo por demanda contratada'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (132,''2301'',''Aquisição de serviço de comunicação para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (133,''2302'',''Aquisição de serviço de comunicação por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (134,''2303'',''Aquisição de serviço de comunicação por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (135,''2304'',''Aquisição de serviço de comunicação por estabelecimento de prestador de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (136,''2305'',''Aquisição de serviço de comunicação por estabelecimento de geradora ou de distribuidora de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (137,''2306'',''Aquisição de serviço de comunicação por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (138,''2351'',''Aquisição de serviço de transporte para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (139,''2352'',''Aquisição de serviço de transporte por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (140,''2353'',''Aquisição de serviço de transporte por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (141,''2354'',''Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (142,''2355'',''Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (143,''2356'',''Aquisição de serviço de transporte por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (144,''2401'',''Compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (145,''2403'',''Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (146,''2406'',''Compra de bem para o ativo imobilizado cuja mercadoria está sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (147,''2407'',''Compra de mercadoria para uso ou consumo cuja mercadoria está sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (148,''2408'',''Transferência para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (149,''2409'',''Transferência para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (150,''2410'',''Devolução de venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (151,''2411'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (152,''2414'',''Retorno de produção do estabelecimento, remetida para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (153,''2415'',''Retorno de mercadoria adquirida ou recebida de terceiros, remetida para venda fora do estabelecimento em operação com mercadoria sujeita ao regime de substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (154,''2501'',''Entrada de mercadoria recebida com fim específico de exportação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (155,''2503'',''Entrada decorrente de devolução de produto remetido com fim específico de exportação, de produção do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (156,''2504'',''Entrada decorrente de devolução de mercadoria remetida com fim específico de exportação, adquirida ou recebida de terceiros'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (157,''2551'',''Compra de bem para o ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (158,''2552'',''Transferência de bem do ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (159,''2553'',''Devolução de venda de bem do ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (160,''2554'',''Retorno de bem do ativo imobilizado remetido para uso fora do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (161,''2555'',''Entrada de bem do ativo imobilizado de terceiro, remetido para uso no estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (162,''2556'',''Compra de material para uso ou consumo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (163,''2557'',''Transferência de material para uso ou consumo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (164,''2603'',''Ressarcimento de ICMS retido por substituição tributária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (165,''2901'',''Entrada para industrialização por encomenda'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (166,''2902'',''Retorno de mercadoria remetida para industrialização por encomenda'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (167,''2903'',''Entrada de mercadoria remetida para industrialização e não aplicada no referido processo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (168,''2904'',''Retorno de remessa para venda fora do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (169,''2905'',''Entrada de mercadoria recebida para depósito em depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (170,''2906'',''Retorno de mercadoria remetida para depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (171,''2907'',''Retorno simbólico de mercadoria remetida para depósito fechado ou armazém geral'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (172,''2908'',''Entrada de bem por conta de contrato de comodato'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (173,''2909'',''Retorno de bem remetido por conta de contrato de comodato'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (174,''2910'',''Entrada de bonificação, doação ou brinde'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (175,''2911'',''Entrada de amostra grátis'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (176,''2912'',''Entrada de mercadoria ou bem recebido para demonstração'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (177,''2913'',''Retorno de mercadoria ou bem remetido para demonstração'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (178,''2914'',''Retorno de mercadoria ou bem remetido para exposição ou feira'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (179,''2915'',''Entrada de mercadoria ou bem recebido para conserto ou reparo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (180,''2916'',''Retorno de mercadoria ou bem remetido para conserto ou reparo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (181,''2917'',''Entrada de mercadoria recebida em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (182,''2918'',''Devolução de mercadoria remetida em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (183,''2919'',''Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, remetida anteriormente em consignação mercantil ou industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (184,''2920'',''Entrada de vasilhame ou sacaria'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (185,''2921'',''Retorno de vasilhame ou sacaria'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (186,''2922'',''Lançamento efetuado a título de simples faturamento decorrente de compra para recebimento futuro'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (187,''2923'',''Entrada de mercadoria recebida do vendedor remetente, em venda à ordem'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (188,''2924'',''Entrada para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (189,''2925'',''Retorno de mercadoria remetida para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (190,''2949'',''Outra entrada de mercadoria ou prestação de serviço não especificado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (191,''3101'',''Compra para industrialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (192,''3102'',''Compra para comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (193,''3126'',''Compra para utilização na prestação de serviço'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (194,''3127'',''Compra para industrialização sob o regime de \"drawback\"'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (195,''3201'',''Devolução de venda de produção do estabelecimento'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (196,''3202'',''Devolução de venda de mercadoria adquirida ou recebida de terceiros'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (197,''3205'',''Anulação de valor relativo à prestação de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (198,''3206'',''Anulação de valor relativo à prestação de serviço de transporte'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (199,''3207'',''Anulação de valor relativo à venda de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (200,''3211'',''Devolução de venda de produção do estabelecimento sob o regime de \"drawback\"'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (201,''3251'',''Compra de energia elétrica para distribuição ou comercialização'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (202,''3301'',''Aquisição de serviço de comunicação para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (203,''3351'',''Aquisição de serviço de transporte para execução de serviço da mesma natureza'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (204,''3352'',''Aquisição de serviço de transporte por estabelecimento industrial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (205,''3353'',''Aquisição de serviço de transporte por estabelecimento comercial'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (206,''3354'',''Aquisição de serviço de transporte por estabelecimento de prestador de serviço de comunicação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (207,''3355'',''Aquisição de serviço de transporte por estabelecimento de geradora ou de distribuidora de energia elétrica'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (208,''3356'',''Aquisição de serviço de transporte por estabelecimento de produtor rural'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (209,''3503'',''Devolução de mercadoria exportada que tenha sido recebida com fim específico de exportação'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (210,''3551'',''Compra de bem para o ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (211,''3553'',''Devolução de venda de bem do ativo imobilizado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (212,''3556'',''Compra de material para uso ou consumo'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (213,''3930'',''Lançamento efetuado a título de entrada de bem sob amparo de regime especial aduaneiro de admissão temporária'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (214,''3949'',''Outra entrada de mercadoria ou prestação de serviço não especificado'',0);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (215,''5101'',''Venda de produção do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (216,''5102'',''Venda de mercadoria adquirida ou recebida de terceiros'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (217,''5103'',''Venda de produção do estabelecimento, efetuada fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (218,''5104'',''Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (219,''5105'',''Venda de produção do estabelecimento que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (220,''5106'',''Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (221,''5109'',''Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (222,''5110'',''Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (223,''5111'',''Venda de produção do estabelecimento remetida anteriormente em consignação industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (224,''5112'',''Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (225,''5113'',''Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (226,''5114'',''Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (227,''5115'',''Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (228,''5116'',''Venda de produção do estabelecimento originada de encomenda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (229,''5117'',''Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (230,''5118'',''Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (231,''5119'',''Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (232,''5120'',''Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (233,''5122'',''Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (234,''5123'',''Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (235,''5124'',''Industrialização efetuada para outra empresa'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (236,''5125'',''Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento adquirent'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (237,''5151'',''Transferência de produção do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (238,''5152'',''Transferência de mercadoria adquirida ou recebida de terceiros'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (239,''5153'',''Transferência de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (240,''5155'',''Transferência de produção do estabelecimento, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (241,''5156'',''Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (242,''5201'',''Devolução de compra para industrialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (243,''5202'',''Devolução de compra para comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (244,''5205'',''Anulação de valor relativo a aquisição de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (245,''5206'',''Anulação de valor relativo a aquisição de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (246,''5207'',''Anulação de valor relativo à compra de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (247,''5208'',''Devolução de mercadoria recebida em transferência para industrialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (248,''5209'',''Devolução de mercadoria recebida em transferência para comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (249,''5210'',''Devolução de compra para utilização na prestação de serviço'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (250,''5251'',''Venda de energia elétrica para distribuição ou comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (251,''5252'',''Venda de energia elétrica para estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (252,''5253'',''Venda de energia elétrica para estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (253,''5254'',''Venda de energia elétrica para estabelecimento prestador de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (254,''5255'',''Venda de energia elétrica para estabelecimento prestador de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (255,''5256'',''Venda de energia elétrica para estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (256,''5257'',''Venda de energia elétrica para consumo por demanda contratada'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (257,''5258'',''Venda de energia elétrica a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (258,''5301'',''Prestação de serviço de comunicação para execução de serviço da mesma natureza'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (259,''5302'',''Prestação de serviço de comunicação a estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (260,''5303'',''Prestação de serviço de comunicação a estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (261,''5304'',''Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (262,''5305'',''Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (263,''5306'',''Prestação de serviço de comunicação a estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (264,''5307'',''Prestação de serviço de comunicação a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (265,''5351'',''Prestação de serviço de transporte para execução de serviço da mesma natureza'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (266,''5352'',''Prestação de serviço de transporte a estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (267,''5353'',''Prestação de serviço de transporte a estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (268,''5354'',''Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (269,''5355'',''Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (270,''5356'',''Prestação de serviço de transporte a estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (271,''5357'',''Prestação de serviço de transporte a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (272,''5401'',''Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (273,''5402'',''Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (274,''5403'',''Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (275,''5405'',''Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituído'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (276,''5408'',''Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (277,''5409'',''Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (278,''5410'',''Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (279,''5411'',''Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (280,''5412'',''Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (281,''5413'',''Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (282,''5414'',''Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (283,''5415'',''Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (284,''5451'',''Remessa de animal e de insumo para estabelecimento produtor'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (285,''5501'',''Remessa de produção do estabelecimento, com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (286,''5502'',''Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (287,''5503'',''Devolução de mercadoria recebida com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (288,''5551'',''Venda de bem do ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (289,''5552'',''Transferência de bem do ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (290,''5553'',''Devolução de compra de bem para o ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (291,''5554'',''Remessa de bem do ativo imobilizado para uso fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (292,''5555'',''Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (293,''5556'',''Devolução de compra de material de uso ou consumo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (294,''5557'',''Transferência de material de uso ou consumo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (295,''5601'',''Transferência de crédito de ICMS acumulado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (296,''5602'',''Transferência de saldo credor de ICMS para outro estabelecimento da mesma empresa, destinado à compensação de saldo devedor de ICMS'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (297,''5603'',''Ressarcimento de ICMS retido por substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (298,''5901'',''Remessa para industrialização por encomenda'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (299,''5902'',''Retorno de mercadoria utilizada na industrialização por encomenda'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (300,''5903'',''Retorno de mercadoria recebida para industrialização e não aplicada no referido processo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (301,''5904'',''Remessa para venda fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (302,''5905'',''Remessa para depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (303,''5906'',''Retorno de mercadoria depositada em depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (304,''5907'',''Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (305,''5908'',''Remessa de bem por conta de contrato de comodato'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (306,''5909'',''Retorno de bem recebido por conta de contrato de comodato'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (307,''5910'',''Remessa em bonificação, doação ou brinde'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (308,''5911'',''Remessa de amostra grátis'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (309,''5912'',''Remessa de mercadoria ou bem para demonstração'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (310,''5913'',''Retorno de mercadoria ou bem recebido para demonstração'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (311,''5914'',''Remessa de mercadoria ou bem para exposição ou feira'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (312,''5915'',''Remessa de mercadoria ou bem para conserto ou reparo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (313,''5916'',''Retorno de mercadoria ou bem recebido para conserto ou reparo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (314,''5917'',''Remessa de mercadoria em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (315,''5918'',''Devolução de mercadoria recebida em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (316,''5919'',''Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (317,''5920'',''Remessa de vasilhame ou sacaria'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (318,''5921'',''Devolução de vasilhame ou sacaria'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (319,''5922'',''Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (320,''5923'',''Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (321,''5924'',''Remessa para industrialização por conta e ordem do adquirente da mercadoria,'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (322,''5925'',''Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (323,''5926'',''Lançamento efetuado a título de reclassificação de mercadoria decorrente de formação de kit ou de sua desagregação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (324,''5927'',''Lançamento efetuado a título de baixa de estoque decorrente de perda, roubo ou deterioração'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (325,''5928'',''Lançamento efetuado a título de baixa de estoque decorrente do encerramento da atividade da empresa'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (326,''5929'',''Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (327,''5931'',''Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pelo serviço de'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (328,''5932'',''Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (329,''5949'',''Outra saída de mercadoria ou prestação de serviço não especificado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (330,''6101'',''Venda de produção do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (331,''6102'',''Venda de mercadoria adquirida ou recebida de terceiros'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (332,''6103'',''Venda de produção do estabelecimento, efetuada fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (333,''6104'',''Venda de mercadoria adquirida ou recebida de terceiros, efetuada fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (334,''6105'',''Venda de produção do estabelecimento que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (335,''6106'',''Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (336,''6107'',''Venda de produção do estabelecimento, destinada a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (337,''6108'',''Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (338,''6109'',''Venda de produção do estabelecimento, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (339,''6110'',''Venda de mercadoria adquirida ou recebida de terceiros, destinada à Zona Franca de Manaus ou Áreas de Livre Comércio'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (340,''6111'',''Venda de produção do estabelecimento remetida anteriormente em consignação industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (341,''6112'',''Venda de mercadoria adquirida ou recebida de Terceiros remetida anteriormente em consignação industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (342,''6113'',''Venda de produção do estabelecimento remetida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (343,''6114'',''Venda de mercadoria adquirida ou recebida de terceiros remetida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (344,''6115'',''Venda de mercadoria adquirida ou recebida de terceiros, recebida anteriormente em consignação mercantil'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (345,''6116'',''Venda de produção do estabelecimento originada de encomenda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (346,''6117'',''Venda de mercadoria adquirida ou recebida de terceiros, originada de encomenda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (347,''6118'',''Venda de produção do estabelecimento entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (348,''6119'',''Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (349,''6120'',''Venda de mercadoria adquirida ou recebida de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (350,''6122'',''Venda de produção do estabelecimento remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (351,''6123'',''Venda de mercadoria adquirida ou recebida de terceiros remetida para industrialização, por conta e ordem do adquirente, sem transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (352,''6124'',''Industrialização efetuada para outra empresa'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (353,''6125'',''Industrialização efetuada para outra empresa quando a mercadoria recebida para utilização no processo de industrialização não transitar pelo estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (354,''6151'',''Transferência de produção do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (355,''6152'',''Transferência de mercadoria adquirida ou recebida de terceiros'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (356,''6153'',''Transferência de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (357,''6155'',''Transferência de produção do estabelecimento, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (358,''6156'',''Transferência de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (359,''6201'',''Devolução de compra para industrialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (360,''6202'',''Devolução de compra para comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (361,''6205'',''Anulação de valor relativo a aquisição de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (362,''6206'',''Anulação de valor relativo a aquisição de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (363,''6207'',''Anulação de valor relativo à compra de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (364,''6208'',''Devolução de mercadoria recebida em transferência para industrialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (365,''6209'',''Devolução de mercadoria recebida em transferência para comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (366,''6210'',''Devolução de compra para utilização na prestação de serviço'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (367,''6251'',''Venda de energia elétrica para distribuição ou comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (368,''6252'',''Venda de energia elétrica para estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (369,''6253'',''Venda de energia elétrica para estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (370,''6254'',''Venda de energia elétrica para estabelecimento prestador de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (371,''6255'',''Venda de energia elétrica para estabelecimento prestador de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (372,''6256'',''Venda de energia elétrica para estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (373,''6257'',''Venda de energia elétrica para consumo por demanda contratada'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (374,''6258'',''Venda de energia elétrica a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (375,''6301'',''Prestação de serviço de comunicação para execução de serviço da mesma natureza'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (376,''6302'',''Prestação de serviço de comunicação a estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (377,''6303'',''Prestação de serviço de comunicação a estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (378,''6304'',''Prestação de serviço de comunicação a estabelecimento de prestador de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (379,''6305'',''Prestação de serviço de comunicação a estabelecimento de geradora ou de distribuidora de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (380,''6306'',''Prestação de serviço de comunicação a estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (381,''6307'',''Prestação de serviço de comunicação a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (382,''6351'',''Prestação de serviço de transporte para execução de serviço da mesma natureza'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (383,''6352'',''Prestação de serviço de transporte a estabelecimento industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (384,''6353'',''Prestação de serviço de transporte a estabelecimento comercial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (385,''6354'',''Prestação de serviço de transporte a estabelecimento de prestador de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (386,''6355'',''Prestação de serviço de transporte a estabelecimento de geradora ou de distribuidora de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (387,''6356'',''Prestação de serviço de transporte a estabelecimento de produtor rural'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (388,''6357'',''Prestação de serviço de transporte a não contribuinte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (389,''6401'',''Venda de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária, na condição de contribuinte substituto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (390,''6402'',''Venda de produção do estabelecimento de produto sujeito ao regime de substituição tributária, em operação entre contribuintes substitutos do mesmo produto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (391,''6403'',''Venda de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária, na condição de contribuinte substituto'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (392,''6404'',''Venda de mercadoria sujeita ao regime de substituição tributária, cujo imposto já tenha sido retido anteriormente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (393,''6408'',''Transferência de produção do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (394,''6409'',''Transferência de mercadoria adquirida ou recebida de terceiros em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (395,''6410'',''Devolução de compra para industrialização em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (396,''6411'',''Devolução de compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (397,''6412'',''Devolução de bem do ativo imobilizado, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (398,''6413'',''Devolução de mercadoria destinada ao uso ou consumo, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (399,''6414'',''Remessa de produção do estabelecimento para venda fora do estabelecimento em operação com produto sujeito ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (400,''6415'',''Remessa de mercadoria adquirida ou recebida de terceiros para venda fora do estabelecimento, em operação com mercadoria sujeita ao regime de substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (401,''6501'',''Remessa de produção do estabelecimento, com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (402,''6502'',''Remessa de mercadoria adquirida ou recebida de terceiros, com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (403,''6503'',''Devolução de mercadoria recebida com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (404,''6551'',''Venda de bem do ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (405,''6552'',''Transferência de bem do ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (406,''6553'',''Devolução de compra de bem para o ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (407,''6554'',''Remessa de bem do ativo imobilizado para uso fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (408,''6555'',''Devolução de bem do ativo imobilizado de terceiro, recebido para uso no estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (409,''6556'',''Devolução de compra de material de uso ou consumo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (410,''6557'',''Transferência de material de uso ou consumo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (411,''6603'',''Ressarcimento de ICMS retido por substituição tributária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (412,''6901'',''Remessa para industrialização por encomenda'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (413,''6902'',''Retorno de mercadoria utilizada na industrialização por encomenda'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (414,''6903'',''Retorno de mercadoria recebida para industrialização e não aplicada no referido processo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (415,''6904'',''Remessa para venda fora do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (416,''6905'',''Remessa para depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (417,''6906'',''Retorno de mercadoria depositada em depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (418,''6907'',''Retorno simbólico de mercadoria depositada em depósito fechado ou armazém geral'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (419,''6908'',''Remessa de bem por conta de contrato de comodato'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (420,''6909'',''Retorno de bem recebido por conta de contrato de comodato'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (421,''6910'',''Remessa em bonificação, doação ou brinde'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (422,''6911'',''Remessa de amostra grátis'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (423,''6912'',''Remessa de mercadoria ou bem para demonstração'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (424,''6913'',''Retorno de mercadoria ou bem recebido para demonstração'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (425,''6914'',''Remessa de mercadoria ou bem para exposição ou feira'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (426,''6915'',''Remessa de mercadoria ou bem para conserto ou reparo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (427,''6916'',''Retorno de mercadoria ou bem recebido para conserto ou reparo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (428,''6917'',''Remessa de mercadoria em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (429,''6918'',''Devolução de mercadoria recebida em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (430,''6919'',''Devolução simbólica de mercadoria vendida ou utilizada em processo industrial, recebida anteriormente em consignação mercantil ou industrial'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (431,''6920'',''Remessa de vasilhame ou sacaria'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (432,''6921'',''Devolução de vasilhame ou sacaria'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (433,''6922'',''Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (434,''6923'',''Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (435,''6924'',''Remessa para industrialização por conta e ordem do adquirente da mercadoria, quando esta não transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (436,''6925'',''Retorno de mercadoria recebida para industrialização por conta e ordem do adquirente da mercadoria, quando aquela não transitar pelo estabelecimento do adquirente'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (437,''6929'',''Lançamento efetuado em decorrência de emissão de documento fiscal relativo a operação ou prestação também registrada em equipamento Emissor de Cupom Fiscal'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (438,''6931'',''Lançamento efetuado em decorrência da responsabilidade de retenção do imposto por substituição tributária, atribuída ao remetente ou alienante da mercadoria, pel'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (439,''6932'',''Prestação de serviço de transporte iniciada em unidade da Federação diversa daquela onde inscrito o prestador'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (440,''6949'',''Outra saída de mercadoria ou prestação de serviço não especificado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (441,''7101'',''Venda de produção do estabelecimento'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (442,''7102'',''Venda de mercadoria adquirida ou recebida de terceiros'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (443,''7105'',''Venda de produção do estabelecimento, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (444,''7106'',''Venda de mercadoria adquirida ou recebida de terceiros, que não deva por ele transitar'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (445,''7127'',''Venda de produção do estabelecimento sob o regime de \"drawback\"'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (446,''7201'',''Devolução de compra para industrialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (447,''7202'',''Devolução de compra para comercialização'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (448,''7205'',''Anulação de valor relativo à aquisição de serviço de comunicação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (449,''7206'',''Anulação de valor relativo a aquisição de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (450,''7207'',''Anulação de valor relativo à compra de energia elétrica'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (451,''7210'',''Devolução de compra para utilização na prestação de serviço'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (452,''7211'',''Devolução de compras para industrialização sob o regime de drawback\"'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (453,''7251'',''Venda de energia elétrica para o exterior'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (454,''7301'',''Prestação de serviço de comunicação para execução de serviço da mesma natureza'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (455,''7358'',''Prestação de serviço de transporte'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (456,''7501'',''Exportação de mercadorias recebidas com fim específico de exportação'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (457,''7551'',''Venda de bem do ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (458,''7553'',''Devolução de compra de bem para o ativo imobilizado'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (459,''7556'',''Devolução de compra de material de uso ou consumo'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (460,''7930'',''Lançamento efetuado a título de devolução de bem cuja entrada tenha ocorrido sob amparo de regime especial aduaneiro de admissão temporária'',1);');
  lStrList.Value.Add('INSERT INTO `cfop` (`id`,`code`,`name`,`operation_type`) VALUES (461,''7949'',''Outra saída de mercadoria ou prestação de serviço não especificado'',1);');

  Result := lStrList.Value.Text;
end;

end.
